name = "FG"
version = "0.1.0"
defaultTargets = ["FG"]
testDriver = "PacoTest"

[[lean_lib]]
name = "FG"

[[lean_lib]]
name = "Paco"
globs = ["Paco", "Paco.+"]

[[lean_lib]]
name = "PacoTest"
globs = ["PacoTest.+"]
